### ISSUE TITLE
Which repo is the canonical source?

### ISSUE THREAD

**Issue by ryanmaxwell** [williamFalcon/SwiftTryCatch#11]
Hi there - I'm using this as a pod in my project. I'm wondering which repo is the canonical source as I have a patch I'd like to submit as a PR to you.

The pod points at the fork of this code living at https://github.com/cfr/SwiftTryCatch.git 
However it's a few commits behind this project now. 

Perhaps you can reclaim the pod from cfr as you are the project author, and continue the updates?

**Comment by williamFalcon** [comment]
This one is. Someone highjacked the pod ownership for some reason. Submit here and I'll figure it out with the cocoapods people.

**Comment by ryanmaxwell** [comment]
Cool, have opened 2 PRs. One adds obj-c annotations for nullability and closure type; the other updates the naming which you may or may not be on board with.
