### ISSUE TITLE
Nothing is happening

### ISSUE THREAD

**Issue by Riccardo99** [williamFalcon/SwiftTryCatch#4]
Hi everybody ^^

I'm trying to use the following code, but I'm getting no `println` exit with it.

    var x: Int! = nil
    
    SwiftTryCatch.try({
        println("x: \(x!)")
        }, catch: { (error) in
            println("catch!!!")
        }, finally: {
            println("finally!!!")
        }
    )

I added the *header* to my project normally and used the `#import` without receiving any errors. My code is **compiling** without problems, but when I run it **nothing happens**. Even the `printl` inside the `finally` block is not running.

Am I doing something wrong?

Thanks ^^

**Comment by williamFalcon** [comment]
It's working fine. Here is a demo. https://www.dropbox.com/sh/cmrb0tdj1jpp8jo/AADKQP7Q7Z6-DwdPnMNmEQmka?dl=0

**Comment by Riccardo99** [comment]
I tried it in the demo you send me, but it didn't work. The example you send in the demo works, but not this code I talk in the message, somehow when I try things like: 
    var x: Int? = nil
    var y = x!
The error `fatal error: unexpectedly found nil while unwrapping an Optional value` is not being caught.
