### ISSUE TITLE
Use of Unresolved identifier 'SwiftTryCatch'

### ISSUE THREAD

**Issue by InfiniteRandomVariable** [williamFalcon/SwiftTryCatch#5]
I suspect follow this step might solve the problem. 
http://stackoverflow.com/questions/24146677/swift-bridging-header-import-issue
https://www.dropbox.com/sh/cmrb0tdj1jpp8jo/AADKQP7Q7Z6-DwdPnMNmEQmka?dl=0

It keeps returning this compile time error in Swift 1.2 XCode 6.3.1

           SwiftTryCatch().try({
                    
                    
                    // try something
                    }, catch: { (error) in
                        
                        println("\(error.description)")
                        
                    }, finally: {
                        // close resources
                        
                        
               })

**Comment by evermeer** [comment]
For SwiftTryCatch you do not need a bridging header. It's already written in Swift. What you do need is an import line like this:
```
import SwiftTryCatch
```
