### ISSUE TITLE
It won't do whats its supposed to

### ISSUE THREAD

**Issue by SahandTheGreat** [williamFalcon/SwiftTryCatch#6]
In the try code i still get an exception and the app crashes instead of doing the code in catch.
PleAse hElp mE

**Comment by zdesiree** [comment]
Same here :(

**Comment by ArkadiYoskovitz** [comment]
you need to change the method signature, it shouldn't include language reserved words.

This worked for me:
in the header:
+(void)tryRun:(void (^)())tryRun catchRun:(void (^)(NSException *))catchRun finallyRun:(void (^)())finallyRun;

in the implementation:
+(void)tryRun:(void (^)())tryRun catchRun:(void (^)(NSException *))catchRun finallyRun:(void (^)())finallyRun {
    @try {
        tryRun ? tryRun() : nil;
    }
    
    @catch (NSException *exception) {
        catchRun ? catchRun(exception) : nil;
    }
    @finally {
        finallyRun ? finallyRun() : nil;
    }
}

in swift code:

SwiftTryCatch.tryRun({
                    // code to try
                }, catchRun: { (error) in
                    // code to handle exception
                }, finallyRun: {
                    // code to do any way
            })
