### ISSUE TITLE
"try" is a reserved word in Swift 2

### ISSUE THREAD

**Issue by DanieleCeglia** [williamFalcon/SwiftTryCatch#7]
Hello I'm trying to use  SwiftTryCatch via Cocoapods, but in Xcode 7.3 this code won't compile:

```
SwiftTryCatch.try(
     {
         // stuff...
     },
     catch:
     { (exception) in
         // stuff...
     },
     finally:
     {
         // stuff...
     }
 )
```

I suggest to rename try in tryBlock, catch in catchBlock and finally in finallyBlock...

**Comment by joshavant** [comment]
For those landing on this question in the future, you'll need to escape 'try', like so:
```
SwiftTryCatch.`try`(
     {
         // stuff...
     },
     catch:
     { (exception) in
         // stuff...
     },
     finally:
     {
         // stuff...
     }
 )
```

**Comment by DanieleCeglia** [comment]
Ok, thanks!

**Comment by souzainf3** [comment]
Use https://github.com/inthepocket/SwiftTryCatch.git or hang on "pull request".

**Comment by williamFalcon** [comment]
Merged pull request
